galaxy_info:
  author: Muhammad Essam
  description: Run PHP container after pulling image
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9

dependencies: []
