---
galaxy_info:
  author: Muhammad Essam
  role_name: install_docker
  description: pull image and run a container with copy file from host into it.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
